apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: cpwallah/todo-app-week-39:fd24e144246f78059acbef3be46a55a544d886e6
    ports:
    - containerPort: 80
    ---
    apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: cpwallah/todo-app-week-39:fd24e144246f78059acbef3be46a55a544d886e6
    ports:
    - containerPort: 80
