apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: cpwallah/todo-app-week-39:d6b6b1c46594f8d3a9383bdfb06aac2eeb2e17d5
    ports:
    - containerPort: 80
    ---
    apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: cpwallah/todo-app-week-39:d6b6b1c46594f8d3a9383bdfb06aac2eeb2e17d5
    ports:
    - containerPort: 80
